### ISSUE TITLE
ÇA MARCHE PAS BORDEL

### ISSUE THREAD

**Issue by LeCoupa** [ArnaudLda/VIE#1]
Ça se lance comment ton machin? Et le README???

**Comment by ArnaudLda** [comment]
Mdrrrr le tarba non mais je testais des trucs pour une boîte et si ça
fonctionne nom de dieuuuu mais là je bidouille un peu c'est pas terminé. En
fait c'est un test pour un VIE

Le 29 nov. 2017 1:39 AM, "Julien Le Coupanec" <notifications@github.com> a
écrit :

**Comment by LeCoupa** [comment]
Haha :)

**Comment by ArnaudLda** [comment]
Mdrrrr mais nikoumouk c'est pas pour toi et c'est pas fini normal
Y a rien pour le moment j'ai juste viteuf fais les taches gulp pour la
minification et le passage du SCSS en CSS
En gros faut lancer la tâche gulp sinon juste tu cliques sur l'index.html
Apres faut que je le règle pour qu'il minifie d'abord jquery avant mon js

Le 29 nov. 2017 1:39 AM, "Julien Le Coupanec" <notifications@github.com> a
écrit :
